// packages/projects/carousel-vue/src/App.vue
<script setup lang='ts'>
import { isPrime } from './need-tree-shake'
import Carousel_0_0 from './components/Carousel_0_0.vue'
import Carousel_1_0 from './components/Carousel_1_0.vue'
import Carousel_1_1 from './components/Carousel_1_1.vue'
import Carousel_2_0 from './components/Carousel_2_0.vue'
import Carousel_2_1 from './components/Carousel_2_1.vue'
import Carousel_2_2 from './components/Carousel_2_2.vue'
import Carousel_3_0 from './components/Carousel_3_0.vue'
import Carousel_3_1 from './components/Carousel_3_1.vue'
import Carousel_3_2 from './components/Carousel_3_2.vue'
import Carousel_3_3 from './components/Carousel_3_3.vue'
import Carousel_4_0 from './components/Carousel_4_0.vue'
import Carousel_4_1 from './components/Carousel_4_1.vue'
import Carousel_4_2 from './components/Carousel_4_2.vue'
import Carousel_4_3 from './components/Carousel_4_3.vue'
import Carousel_4_4 from './components/Carousel_4_4.vue'
import Carousel_5_0 from './components/Carousel_5_0.vue'
import Carousel_5_1 from './components/Carousel_5_1.vue'
import Carousel_5_2 from './components/Carousel_5_2.vue'
import Carousel_5_3 from './components/Carousel_5_3.vue'
import Carousel_5_4 from './components/Carousel_5_4.vue'
import Carousel_5_5 from './components/Carousel_5_5.vue'
import Carousel_6_0 from './components/Carousel_6_0.vue'
import Carousel_6_1 from './components/Carousel_6_1.vue'
import Carousel_6_2 from './components/Carousel_6_2.vue'
import Carousel_6_3 from './components/Carousel_6_3.vue'
import Carousel_6_4 from './components/Carousel_6_4.vue'
import Carousel_6_5 from './components/Carousel_6_5.vue'
import Carousel_6_6 from './components/Carousel_6_6.vue'
import Carousel_7_0 from './components/Carousel_7_0.vue'
import Carousel_7_1 from './components/Carousel_7_1.vue'
import Carousel_7_2 from './components/Carousel_7_2.vue'
import Carousel_7_3 from './components/Carousel_7_3.vue'
import Carousel_7_4 from './components/Carousel_7_4.vue'
import Carousel_7_5 from './components/Carousel_7_5.vue'
import Carousel_7_6 from './components/Carousel_7_6.vue'
import Carousel_7_7 from './components/Carousel_7_7.vue'
import Carousel_8_0 from './components/Carousel_8_0.vue'
import Carousel_8_1 from './components/Carousel_8_1.vue'
import Carousel_8_2 from './components/Carousel_8_2.vue'
import Carousel_8_3 from './components/Carousel_8_3.vue'
import Carousel_8_4 from './components/Carousel_8_4.vue'
import Carousel_8_5 from './components/Carousel_8_5.vue'
import Carousel_8_6 from './components/Carousel_8_6.vue'
import Carousel_8_7 from './components/Carousel_8_7.vue'
import Carousel_8_8 from './components/Carousel_8_8.vue'
import Carousel_9_0 from './components/Carousel_9_0.vue'
import Carousel_9_1 from './components/Carousel_9_1.vue'
import Carousel_9_2 from './components/Carousel_9_2.vue'
import Carousel_9_3 from './components/Carousel_9_3.vue'
import Carousel_9_4 from './components/Carousel_9_4.vue'
import Carousel_9_5 from './components/Carousel_9_5.vue'
import Carousel_9_6 from './components/Carousel_9_6.vue'
import Carousel_9_7 from './components/Carousel_9_7.vue'
import Carousel_9_8 from './components/Carousel_9_8.vue'
import Carousel_9_9 from './components/Carousel_9_9.vue'
import Carousel_10_0 from './components/Carousel_10_0.vue'
import Carousel_10_1 from './components/Carousel_10_1.vue'
import Carousel_10_2 from './components/Carousel_10_2.vue'
import Carousel_10_3 from './components/Carousel_10_3.vue'
import Carousel_10_4 from './components/Carousel_10_4.vue'
import Carousel_10_5 from './components/Carousel_10_5.vue'
import Carousel_10_6 from './components/Carousel_10_6.vue'
import Carousel_10_7 from './components/Carousel_10_7.vue'
import Carousel_10_8 from './components/Carousel_10_8.vue'
import Carousel_10_9 from './components/Carousel_10_9.vue'
import Carousel_10_10 from './components/Carousel_10_10.vue'
import Carousel_11_0 from './components/Carousel_11_0.vue'
import Carousel_11_1 from './components/Carousel_11_1.vue'
import Carousel_11_2 from './components/Carousel_11_2.vue'
import Carousel_11_3 from './components/Carousel_11_3.vue'
import Carousel_11_4 from './components/Carousel_11_4.vue'
import Carousel_11_5 from './components/Carousel_11_5.vue'
import Carousel_11_6 from './components/Carousel_11_6.vue'
import Carousel_11_7 from './components/Carousel_11_7.vue'
import Carousel_11_8 from './components/Carousel_11_8.vue'
import Carousel_11_9 from './components/Carousel_11_9.vue'
import Carousel_11_10 from './components/Carousel_11_10.vue'
import Carousel_11_11 from './components/Carousel_11_11.vue'
import Carousel_12_0 from './components/Carousel_12_0.vue'
import Carousel_12_1 from './components/Carousel_12_1.vue'
import Carousel_12_2 from './components/Carousel_12_2.vue'
import Carousel_12_3 from './components/Carousel_12_3.vue'
import Carousel_12_4 from './components/Carousel_12_4.vue'
import Carousel_12_5 from './components/Carousel_12_5.vue'
import Carousel_12_6 from './components/Carousel_12_6.vue'
import Carousel_12_7 from './components/Carousel_12_7.vue'
import Carousel_12_8 from './components/Carousel_12_8.vue'
import Carousel_12_9 from './components/Carousel_12_9.vue'
import Carousel_12_10 from './components/Carousel_12_10.vue'
import Carousel_12_11 from './components/Carousel_12_11.vue'
import Carousel_12_12 from './components/Carousel_12_12.vue'
import Carousel_13_0 from './components/Carousel_13_0.vue'
import Carousel_13_1 from './components/Carousel_13_1.vue'
import Carousel_13_2 from './components/Carousel_13_2.vue'
import Carousel_13_3 from './components/Carousel_13_3.vue'
import Carousel_13_4 from './components/Carousel_13_4.vue'
import Carousel_13_5 from './components/Carousel_13_5.vue'
import Carousel_13_6 from './components/Carousel_13_6.vue'
import Carousel_13_7 from './components/Carousel_13_7.vue'
import Carousel_13_8 from './components/Carousel_13_8.vue'
import Carousel_13_9 from './components/Carousel_13_9.vue'
import Carousel_13_10 from './components/Carousel_13_10.vue'
import Carousel_13_11 from './components/Carousel_13_11.vue'
import Carousel_13_12 from './components/Carousel_13_12.vue'
import Carousel_13_13 from './components/Carousel_13_13.vue'
import Carousel_14_0 from './components/Carousel_14_0.vue'
import Carousel_14_1 from './components/Carousel_14_1.vue'
import Carousel_14_2 from './components/Carousel_14_2.vue'
import Carousel_14_3 from './components/Carousel_14_3.vue'
import Carousel_14_4 from './components/Carousel_14_4.vue'
import Carousel_14_5 from './components/Carousel_14_5.vue'
import Carousel_14_6 from './components/Carousel_14_6.vue'
import Carousel_14_7 from './components/Carousel_14_7.vue'
import Carousel_14_8 from './components/Carousel_14_8.vue'
import Carousel_14_9 from './components/Carousel_14_9.vue'
import Carousel_14_10 from './components/Carousel_14_10.vue'
import Carousel_14_11 from './components/Carousel_14_11.vue'
import Carousel_14_12 from './components/Carousel_14_12.vue'
import Carousel_14_13 from './components/Carousel_14_13.vue'
import Carousel_14_14 from './components/Carousel_14_14.vue'
import Carousel_15_0 from './components/Carousel_15_0.vue'
import Carousel_15_1 from './components/Carousel_15_1.vue'
import Carousel_15_2 from './components/Carousel_15_2.vue'
import Carousel_15_3 from './components/Carousel_15_3.vue'
import Carousel_15_4 from './components/Carousel_15_4.vue'
import Carousel_15_5 from './components/Carousel_15_5.vue'
import Carousel_15_6 from './components/Carousel_15_6.vue'
import Carousel_15_7 from './components/Carousel_15_7.vue'
import Carousel_15_8 from './components/Carousel_15_8.vue'
import Carousel_15_9 from './components/Carousel_15_9.vue'
import Carousel_15_10 from './components/Carousel_15_10.vue'
import Carousel_15_11 from './components/Carousel_15_11.vue'
import Carousel_15_12 from './components/Carousel_15_12.vue'
import Carousel_15_13 from './components/Carousel_15_13.vue'
import Carousel_15_14 from './components/Carousel_15_14.vue'
import Carousel_15_15 from './components/Carousel_15_15.vue'
import Carousel_16_0 from './components/Carousel_16_0.vue'
import Carousel_16_1 from './components/Carousel_16_1.vue'
import Carousel_16_2 from './components/Carousel_16_2.vue'
import Carousel_16_3 from './components/Carousel_16_3.vue'
import Carousel_16_4 from './components/Carousel_16_4.vue'
import Carousel_16_5 from './components/Carousel_16_5.vue'
import Carousel_16_6 from './components/Carousel_16_6.vue'
import Carousel_16_7 from './components/Carousel_16_7.vue'
import Carousel_16_8 from './components/Carousel_16_8.vue'
import Carousel_16_9 from './components/Carousel_16_9.vue'
import Carousel_16_10 from './components/Carousel_16_10.vue'
import Carousel_16_11 from './components/Carousel_16_11.vue'
import Carousel_16_12 from './components/Carousel_16_12.vue'
import Carousel_16_13 from './components/Carousel_16_13.vue'
import Carousel_16_14 from './components/Carousel_16_14.vue'
import Carousel_16_15 from './components/Carousel_16_15.vue'
import Carousel_16_16 from './components/Carousel_16_16.vue'
import Carousel_17_0 from './components/Carousel_17_0.vue'
import Carousel_17_1 from './components/Carousel_17_1.vue'
import Carousel_17_2 from './components/Carousel_17_2.vue'
import Carousel_17_3 from './components/Carousel_17_3.vue'
import Carousel_17_4 from './components/Carousel_17_4.vue'
import Carousel_17_5 from './components/Carousel_17_5.vue'
import Carousel_17_6 from './components/Carousel_17_6.vue'
import Carousel_17_7 from './components/Carousel_17_7.vue'
import Carousel_17_8 from './components/Carousel_17_8.vue'
import Carousel_17_9 from './components/Carousel_17_9.vue'
import Carousel_17_10 from './components/Carousel_17_10.vue'
import Carousel_17_11 from './components/Carousel_17_11.vue'
import Carousel_17_12 from './components/Carousel_17_12.vue'
import Carousel_17_13 from './components/Carousel_17_13.vue'
import Carousel_17_14 from './components/Carousel_17_14.vue'
import Carousel_17_15 from './components/Carousel_17_15.vue'
import Carousel_17_16 from './components/Carousel_17_16.vue'
import Carousel_17_17 from './components/Carousel_17_17.vue'
import Carousel_18_0 from './components/Carousel_18_0.vue'
import Carousel_18_1 from './components/Carousel_18_1.vue'
import Carousel_18_2 from './components/Carousel_18_2.vue'
import Carousel_18_3 from './components/Carousel_18_3.vue'
import Carousel_18_4 from './components/Carousel_18_4.vue'
import Carousel_18_5 from './components/Carousel_18_5.vue'
import Carousel_18_6 from './components/Carousel_18_6.vue'
import Carousel_18_7 from './components/Carousel_18_7.vue'
import Carousel_18_8 from './components/Carousel_18_8.vue'
import Carousel_18_9 from './components/Carousel_18_9.vue'
import Carousel_18_10 from './components/Carousel_18_10.vue'
import Carousel_18_11 from './components/Carousel_18_11.vue'
import Carousel_18_12 from './components/Carousel_18_12.vue'
import Carousel_18_13 from './components/Carousel_18_13.vue'
import Carousel_18_14 from './components/Carousel_18_14.vue'
import Carousel_18_15 from './components/Carousel_18_15.vue'
import Carousel_18_16 from './components/Carousel_18_16.vue'
import Carousel_18_17 from './components/Carousel_18_17.vue'
import Carousel_18_18 from './components/Carousel_18_18.vue'
import Carousel_19_0 from './components/Carousel_19_0.vue'
import Carousel_19_1 from './components/Carousel_19_1.vue'
import Carousel_19_2 from './components/Carousel_19_2.vue'
import Carousel_19_3 from './components/Carousel_19_3.vue'
import Carousel_19_4 from './components/Carousel_19_4.vue'
import Carousel_19_5 from './components/Carousel_19_5.vue'
import Carousel_19_6 from './components/Carousel_19_6.vue'
import Carousel_19_7 from './components/Carousel_19_7.vue'
import Carousel_19_8 from './components/Carousel_19_8.vue'
import Carousel_19_9 from './components/Carousel_19_9.vue'
import Carousel_19_10 from './components/Carousel_19_10.vue'
import Carousel_19_11 from './components/Carousel_19_11.vue'
import Carousel_19_12 from './components/Carousel_19_12.vue'
import Carousel_19_13 from './components/Carousel_19_13.vue'
import Carousel_19_14 from './components/Carousel_19_14.vue'
import Carousel_19_15 from './components/Carousel_19_15.vue'
import Carousel_19_16 from './components/Carousel_19_16.vue'
import Carousel_19_17 from './components/Carousel_19_17.vue'
import Carousel_19_18 from './components/Carousel_19_18.vue'
import Carousel_19_19 from './components/Carousel_19_19.vue'
</script>

<template>
  <div class='root'>
    <div class='wrapper'>
      <Carousel_0_0 />
    </div>

    <div class='wrapper'>
      <Carousel_1_0 />
      <Carousel_1_1 />
    </div>

    <div class='wrapper'>
      <Carousel_2_0 />
      <Carousel_2_1 />
      <Carousel_2_2 />
    </div>

    <div class='wrapper'>
      <Carousel_3_0 />
      <Carousel_3_1 />
      <Carousel_3_2 />
      <Carousel_3_3 />
    </div>

    <div class='wrapper'>
      <Carousel_4_0 />
      <Carousel_4_1 />
      <Carousel_4_2 />
      <Carousel_4_3 />
      <Carousel_4_4 />
    </div>

    <div class='wrapper'>
      <Carousel_5_0 />
      <Carousel_5_1 />
      <Carousel_5_2 />
      <Carousel_5_3 />
      <Carousel_5_4 />
      <Carousel_5_5 />
    </div>

    <div class='wrapper'>
      <Carousel_6_0 />
      <Carousel_6_1 />
      <Carousel_6_2 />
      <Carousel_6_3 />
      <Carousel_6_4 />
      <Carousel_6_5 />
      <Carousel_6_6 />
    </div>

    <div class='wrapper'>
      <Carousel_7_0 />
      <Carousel_7_1 />
      <Carousel_7_2 />
      <Carousel_7_3 />
      <Carousel_7_4 />
      <Carousel_7_5 />
      <Carousel_7_6 />
      <Carousel_7_7 />
    </div>

    <div class='wrapper'>
      <Carousel_8_0 />
      <Carousel_8_1 />
      <Carousel_8_2 />
      <Carousel_8_3 />
      <Carousel_8_4 />
      <Carousel_8_5 />
      <Carousel_8_6 />
      <Carousel_8_7 />
      <Carousel_8_8 />
    </div>

    <div class='wrapper'>
      <Carousel_9_0 />
      <Carousel_9_1 />
      <Carousel_9_2 />
      <Carousel_9_3 />
      <Carousel_9_4 />
      <Carousel_9_5 />
      <Carousel_9_6 />
      <Carousel_9_7 />
      <Carousel_9_8 />
      <Carousel_9_9 />
    </div>

    <div class='wrapper'>
      <Carousel_10_0 />
      <Carousel_10_1 />
      <Carousel_10_2 />
      <Carousel_10_3 />
      <Carousel_10_4 />
      <Carousel_10_5 />
      <Carousel_10_6 />
      <Carousel_10_7 />
      <Carousel_10_8 />
      <Carousel_10_9 />
      <Carousel_10_10 />
    </div>

    <div class='wrapper'>
      <Carousel_11_0 />
      <Carousel_11_1 />
      <Carousel_11_2 />
      <Carousel_11_3 />
      <Carousel_11_4 />
      <Carousel_11_5 />
      <Carousel_11_6 />
      <Carousel_11_7 />
      <Carousel_11_8 />
      <Carousel_11_9 />
      <Carousel_11_10 />
      <Carousel_11_11 />
    </div>

    <div class='wrapper'>
      <Carousel_12_0 />
      <Carousel_12_1 />
      <Carousel_12_2 />
      <Carousel_12_3 />
      <Carousel_12_4 />
      <Carousel_12_5 />
      <Carousel_12_6 />
      <Carousel_12_7 />
      <Carousel_12_8 />
      <Carousel_12_9 />
      <Carousel_12_10 />
      <Carousel_12_11 />
      <Carousel_12_12 />
    </div>

    <div class='wrapper'>
      <Carousel_13_0 />
      <Carousel_13_1 />
      <Carousel_13_2 />
      <Carousel_13_3 />
      <Carousel_13_4 />
      <Carousel_13_5 />
      <Carousel_13_6 />
      <Carousel_13_7 />
      <Carousel_13_8 />
      <Carousel_13_9 />
      <Carousel_13_10 />
      <Carousel_13_11 />
      <Carousel_13_12 />
      <Carousel_13_13 />
    </div>

    <div class='wrapper'>
      <Carousel_14_0 />
      <Carousel_14_1 />
      <Carousel_14_2 />
      <Carousel_14_3 />
      <Carousel_14_4 />
      <Carousel_14_5 />
      <Carousel_14_6 />
      <Carousel_14_7 />
      <Carousel_14_8 />
      <Carousel_14_9 />
      <Carousel_14_10 />
      <Carousel_14_11 />
      <Carousel_14_12 />
      <Carousel_14_13 />
      <Carousel_14_14 />
    </div>

    <div class='wrapper'>
      <Carousel_15_0 />
      <Carousel_15_1 />
      <Carousel_15_2 />
      <Carousel_15_3 />
      <Carousel_15_4 />
      <Carousel_15_5 />
      <Carousel_15_6 />
      <Carousel_15_7 />
      <Carousel_15_8 />
      <Carousel_15_9 />
      <Carousel_15_10 />
      <Carousel_15_11 />
      <Carousel_15_12 />
      <Carousel_15_13 />
      <Carousel_15_14 />
      <Carousel_15_15 />
    </div>

    <div class='wrapper'>
      <Carousel_16_0 />
      <Carousel_16_1 />
      <Carousel_16_2 />
      <Carousel_16_3 />
      <Carousel_16_4 />
      <Carousel_16_5 />
      <Carousel_16_6 />
      <Carousel_16_7 />
      <Carousel_16_8 />
      <Carousel_16_9 />
      <Carousel_16_10 />
      <Carousel_16_11 />
      <Carousel_16_12 />
      <Carousel_16_13 />
      <Carousel_16_14 />
      <Carousel_16_15 />
      <Carousel_16_16 />
    </div>

    <div class='wrapper'>
      <Carousel_17_0 />
      <Carousel_17_1 />
      <Carousel_17_2 />
      <Carousel_17_3 />
      <Carousel_17_4 />
      <Carousel_17_5 />
      <Carousel_17_6 />
      <Carousel_17_7 />
      <Carousel_17_8 />
      <Carousel_17_9 />
      <Carousel_17_10 />
      <Carousel_17_11 />
      <Carousel_17_12 />
      <Carousel_17_13 />
      <Carousel_17_14 />
      <Carousel_17_15 />
      <Carousel_17_16 />
      <Carousel_17_17 />
    </div>

    <div class='wrapper'>
      <Carousel_18_0 />
      <Carousel_18_1 />
      <Carousel_18_2 />
      <Carousel_18_3 />
      <Carousel_18_4 />
      <Carousel_18_5 />
      <Carousel_18_6 />
      <Carousel_18_7 />
      <Carousel_18_8 />
      <Carousel_18_9 />
      <Carousel_18_10 />
      <Carousel_18_11 />
      <Carousel_18_12 />
      <Carousel_18_13 />
      <Carousel_18_14 />
      <Carousel_18_15 />
      <Carousel_18_16 />
      <Carousel_18_17 />
      <Carousel_18_18 />
    </div>

    <div class='wrapper'>
      <Carousel_19_0 />
      <Carousel_19_1 />
      <Carousel_19_2 />
      <Carousel_19_3 />
      <Carousel_19_4 />
      <Carousel_19_5 />
      <Carousel_19_6 />
      <Carousel_19_7 />
      <Carousel_19_8 />
      <Carousel_19_9 />
      <Carousel_19_10 />
      <Carousel_19_11 />
      <Carousel_19_12 />
      <Carousel_19_13 />
      <Carousel_19_14 />
      <Carousel_19_15 />
      <Carousel_19_16 />
      <Carousel_19_17 />
      <Carousel_19_18 />
      <Carousel_19_19 />
    </div>
  </div>
</template>

<style scoped>
.root {
  position: absolute;
  left: 0;
  top: 0;
  margin: 0;
  padding: 0;
  width: 1500px;
}

.wrapper {
  display: flex;
  alignItems: 'center';
  justifyItems: 'center';
}
</style>

// packages/projects/react/src/app/page.tsx
'use client'
import React from 'react';
// @ts-expect-error test for treeshake
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import {isPrime} from "./need-tree-shake";
import Carousel_0_0 from "../components/Carousel_0_0.tsx";
import Carousel_1_0 from "../components/Carousel_1_0.tsx";
import Carousel_1_1 from "../components/Carousel_1_1.tsx";
import Carousel_2_0 from "../components/Carousel_2_0.tsx";
import Carousel_2_1 from "../components/Carousel_2_1.tsx";
import Carousel_2_2 from "../components/Carousel_2_2.tsx";
import Carousel_3_0 from "../components/Carousel_3_0.tsx";
import Carousel_3_1 from "../components/Carousel_3_1.tsx";
import Carousel_3_2 from "../components/Carousel_3_2.tsx";
import Carousel_3_3 from "../components/Carousel_3_3.tsx";
import Carousel_4_0 from "../components/Carousel_4_0.tsx";
import Carousel_4_1 from "../components/Carousel_4_1.tsx";
import Carousel_4_2 from "../components/Carousel_4_2.tsx";
import Carousel_4_3 from "../components/Carousel_4_3.tsx";
import Carousel_4_4 from "../components/Carousel_4_4.tsx";
import Carousel_5_0 from "../components/Carousel_5_0.tsx";
import Carousel_5_1 from "../components/Carousel_5_1.tsx";
import Carousel_5_2 from "../components/Carousel_5_2.tsx";
import Carousel_5_3 from "../components/Carousel_5_3.tsx";
import Carousel_5_4 from "../components/Carousel_5_4.tsx";
import Carousel_5_5 from "../components/Carousel_5_5.tsx";
import Carousel_6_0 from "../components/Carousel_6_0.tsx";
import Carousel_6_1 from "../components/Carousel_6_1.tsx";
import Carousel_6_2 from "../components/Carousel_6_2.tsx";
import Carousel_6_3 from "../components/Carousel_6_3.tsx";
import Carousel_6_4 from "../components/Carousel_6_4.tsx";
import Carousel_6_5 from "../components/Carousel_6_5.tsx";
import Carousel_6_6 from "../components/Carousel_6_6.tsx";
import Carousel_7_0 from "../components/Carousel_7_0.tsx";
import Carousel_7_1 from "../components/Carousel_7_1.tsx";
import Carousel_7_2 from "../components/Carousel_7_2.tsx";
import Carousel_7_3 from "../components/Carousel_7_3.tsx";
import Carousel_7_4 from "../components/Carousel_7_4.tsx";
import Carousel_7_5 from "../components/Carousel_7_5.tsx";
import Carousel_7_6 from "../components/Carousel_7_6.tsx";
import Carousel_7_7 from "../components/Carousel_7_7.tsx";
import Carousel_8_0 from "../components/Carousel_8_0.tsx";
import Carousel_8_1 from "../components/Carousel_8_1.tsx";
import Carousel_8_2 from "../components/Carousel_8_2.tsx";
import Carousel_8_3 from "../components/Carousel_8_3.tsx";
import Carousel_8_4 from "../components/Carousel_8_4.tsx";
import Carousel_8_5 from "../components/Carousel_8_5.tsx";
import Carousel_8_6 from "../components/Carousel_8_6.tsx";
import Carousel_8_7 from "../components/Carousel_8_7.tsx";
import Carousel_8_8 from "../components/Carousel_8_8.tsx";
import Carousel_9_0 from "../components/Carousel_9_0.tsx";
import Carousel_9_1 from "../components/Carousel_9_1.tsx";
import Carousel_9_2 from "../components/Carousel_9_2.tsx";
import Carousel_9_3 from "../components/Carousel_9_3.tsx";
import Carousel_9_4 from "../components/Carousel_9_4.tsx";
import Carousel_9_5 from "../components/Carousel_9_5.tsx";
import Carousel_9_6 from "../components/Carousel_9_6.tsx";
import Carousel_9_7 from "../components/Carousel_9_7.tsx";
import Carousel_9_8 from "../components/Carousel_9_8.tsx";
import Carousel_9_9 from "../components/Carousel_9_9.tsx";
import Carousel_10_0 from "../components/Carousel_10_0.tsx";
import Carousel_10_1 from "../components/Carousel_10_1.tsx";
import Carousel_10_2 from "../components/Carousel_10_2.tsx";
import Carousel_10_3 from "../components/Carousel_10_3.tsx";
import Carousel_10_4 from "../components/Carousel_10_4.tsx";
import Carousel_10_5 from "../components/Carousel_10_5.tsx";
import Carousel_10_6 from "../components/Carousel_10_6.tsx";
import Carousel_10_7 from "../components/Carousel_10_7.tsx";
import Carousel_10_8 from "../components/Carousel_10_8.tsx";
import Carousel_10_9 from "../components/Carousel_10_9.tsx";
import Carousel_10_10 from "../components/Carousel_10_10.tsx";
import Carousel_11_0 from "../components/Carousel_11_0.tsx";
import Carousel_11_1 from "../components/Carousel_11_1.tsx";
import Carousel_11_2 from "../components/Carousel_11_2.tsx";
import Carousel_11_3 from "../components/Carousel_11_3.tsx";
import Carousel_11_4 from "../components/Carousel_11_4.tsx";
import Carousel_11_5 from "../components/Carousel_11_5.tsx";
import Carousel_11_6 from "../components/Carousel_11_6.tsx";
import Carousel_11_7 from "../components/Carousel_11_7.tsx";
import Carousel_11_8 from "../components/Carousel_11_8.tsx";
import Carousel_11_9 from "../components/Carousel_11_9.tsx";
import Carousel_11_10 from "../components/Carousel_11_10.tsx";
import Carousel_11_11 from "../components/Carousel_11_11.tsx";
import Carousel_12_0 from "../components/Carousel_12_0.tsx";
import Carousel_12_1 from "../components/Carousel_12_1.tsx";
import Carousel_12_2 from "../components/Carousel_12_2.tsx";
import Carousel_12_3 from "../components/Carousel_12_3.tsx";
import Carousel_12_4 from "../components/Carousel_12_4.tsx";
import Carousel_12_5 from "../components/Carousel_12_5.tsx";
import Carousel_12_6 from "../components/Carousel_12_6.tsx";
import Carousel_12_7 from "../components/Carousel_12_7.tsx";
import Carousel_12_8 from "../components/Carousel_12_8.tsx";
import Carousel_12_9 from "../components/Carousel_12_9.tsx";
import Carousel_12_10 from "../components/Carousel_12_10.tsx";
import Carousel_12_11 from "../components/Carousel_12_11.tsx";
import Carousel_12_12 from "../components/Carousel_12_12.tsx";
import Carousel_13_0 from "../components/Carousel_13_0.tsx";
import Carousel_13_1 from "../components/Carousel_13_1.tsx";
import Carousel_13_2 from "../components/Carousel_13_2.tsx";
import Carousel_13_3 from "../components/Carousel_13_3.tsx";
import Carousel_13_4 from "../components/Carousel_13_4.tsx";
import Carousel_13_5 from "../components/Carousel_13_5.tsx";
import Carousel_13_6 from "../components/Carousel_13_6.tsx";
import Carousel_13_7 from "../components/Carousel_13_7.tsx";
import Carousel_13_8 from "../components/Carousel_13_8.tsx";
import Carousel_13_9 from "../components/Carousel_13_9.tsx";
import Carousel_13_10 from "../components/Carousel_13_10.tsx";
import Carousel_13_11 from "../components/Carousel_13_11.tsx";
import Carousel_13_12 from "../components/Carousel_13_12.tsx";
import Carousel_13_13 from "../components/Carousel_13_13.tsx";
import Carousel_14_0 from "../components/Carousel_14_0.tsx";
import Carousel_14_1 from "../components/Carousel_14_1.tsx";
import Carousel_14_2 from "../components/Carousel_14_2.tsx";
import Carousel_14_3 from "../components/Carousel_14_3.tsx";
import Carousel_14_4 from "../components/Carousel_14_4.tsx";
import Carousel_14_5 from "../components/Carousel_14_5.tsx";
import Carousel_14_6 from "../components/Carousel_14_6.tsx";
import Carousel_14_7 from "../components/Carousel_14_7.tsx";
import Carousel_14_8 from "../components/Carousel_14_8.tsx";
import Carousel_14_9 from "../components/Carousel_14_9.tsx";
import Carousel_14_10 from "../components/Carousel_14_10.tsx";
import Carousel_14_11 from "../components/Carousel_14_11.tsx";
import Carousel_14_12 from "../components/Carousel_14_12.tsx";
import Carousel_14_13 from "../components/Carousel_14_13.tsx";
import Carousel_14_14 from "../components/Carousel_14_14.tsx";
import Carousel_15_0 from "../components/Carousel_15_0.tsx";
import Carousel_15_1 from "../components/Carousel_15_1.tsx";
import Carousel_15_2 from "../components/Carousel_15_2.tsx";
import Carousel_15_3 from "../components/Carousel_15_3.tsx";
import Carousel_15_4 from "../components/Carousel_15_4.tsx";
import Carousel_15_5 from "../components/Carousel_15_5.tsx";
import Carousel_15_6 from "../components/Carousel_15_6.tsx";
import Carousel_15_7 from "../components/Carousel_15_7.tsx";
import Carousel_15_8 from "../components/Carousel_15_8.tsx";
import Carousel_15_9 from "../components/Carousel_15_9.tsx";
import Carousel_15_10 from "../components/Carousel_15_10.tsx";
import Carousel_15_11 from "../components/Carousel_15_11.tsx";
import Carousel_15_12 from "../components/Carousel_15_12.tsx";
import Carousel_15_13 from "../components/Carousel_15_13.tsx";
import Carousel_15_14 from "../components/Carousel_15_14.tsx";
import Carousel_15_15 from "../components/Carousel_15_15.tsx";
import Carousel_16_0 from "../components/Carousel_16_0.tsx";
import Carousel_16_1 from "../components/Carousel_16_1.tsx";
import Carousel_16_2 from "../components/Carousel_16_2.tsx";
import Carousel_16_3 from "../components/Carousel_16_3.tsx";
import Carousel_16_4 from "../components/Carousel_16_4.tsx";
import Carousel_16_5 from "../components/Carousel_16_5.tsx";
import Carousel_16_6 from "../components/Carousel_16_6.tsx";
import Carousel_16_7 from "../components/Carousel_16_7.tsx";
import Carousel_16_8 from "../components/Carousel_16_8.tsx";
import Carousel_16_9 from "../components/Carousel_16_9.tsx";
import Carousel_16_10 from "../components/Carousel_16_10.tsx";
import Carousel_16_11 from "../components/Carousel_16_11.tsx";
import Carousel_16_12 from "../components/Carousel_16_12.tsx";
import Carousel_16_13 from "../components/Carousel_16_13.tsx";
import Carousel_16_14 from "../components/Carousel_16_14.tsx";
import Carousel_16_15 from "../components/Carousel_16_15.tsx";
import Carousel_16_16 from "../components/Carousel_16_16.tsx";
import Carousel_17_0 from "../components/Carousel_17_0.tsx";
import Carousel_17_1 from "../components/Carousel_17_1.tsx";
import Carousel_17_2 from "../components/Carousel_17_2.tsx";
import Carousel_17_3 from "../components/Carousel_17_3.tsx";
import Carousel_17_4 from "../components/Carousel_17_4.tsx";
import Carousel_17_5 from "../components/Carousel_17_5.tsx";
import Carousel_17_6 from "../components/Carousel_17_6.tsx";
import Carousel_17_7 from "../components/Carousel_17_7.tsx";
import Carousel_17_8 from "../components/Carousel_17_8.tsx";
import Carousel_17_9 from "../components/Carousel_17_9.tsx";
import Carousel_17_10 from "../components/Carousel_17_10.tsx";
import Carousel_17_11 from "../components/Carousel_17_11.tsx";
import Carousel_17_12 from "../components/Carousel_17_12.tsx";
import Carousel_17_13 from "../components/Carousel_17_13.tsx";
import Carousel_17_14 from "../components/Carousel_17_14.tsx";
import Carousel_17_15 from "../components/Carousel_17_15.tsx";
import Carousel_17_16 from "../components/Carousel_17_16.tsx";
import Carousel_17_17 from "../components/Carousel_17_17.tsx";
import Carousel_18_0 from "../components/Carousel_18_0.tsx";
import Carousel_18_1 from "../components/Carousel_18_1.tsx";
import Carousel_18_2 from "../components/Carousel_18_2.tsx";
import Carousel_18_3 from "../components/Carousel_18_3.tsx";
import Carousel_18_4 from "../components/Carousel_18_4.tsx";
import Carousel_18_5 from "../components/Carousel_18_5.tsx";
import Carousel_18_6 from "../components/Carousel_18_6.tsx";
import Carousel_18_7 from "../components/Carousel_18_7.tsx";
import Carousel_18_8 from "../components/Carousel_18_8.tsx";
import Carousel_18_9 from "../components/Carousel_18_9.tsx";
import Carousel_18_10 from "../components/Carousel_18_10.tsx";
import Carousel_18_11 from "../components/Carousel_18_11.tsx";
import Carousel_18_12 from "../components/Carousel_18_12.tsx";
import Carousel_18_13 from "../components/Carousel_18_13.tsx";
import Carousel_18_14 from "../components/Carousel_18_14.tsx";
import Carousel_18_15 from "../components/Carousel_18_15.tsx";
import Carousel_18_16 from "../components/Carousel_18_16.tsx";
import Carousel_18_17 from "../components/Carousel_18_17.tsx";
import Carousel_18_18 from "../components/Carousel_18_18.tsx";
import Carousel_19_0 from "../components/Carousel_19_0.tsx";
import Carousel_19_1 from "../components/Carousel_19_1.tsx";
import Carousel_19_2 from "../components/Carousel_19_2.tsx";
import Carousel_19_3 from "../components/Carousel_19_3.tsx";
import Carousel_19_4 from "../components/Carousel_19_4.tsx";
import Carousel_19_5 from "../components/Carousel_19_5.tsx";
import Carousel_19_6 from "../components/Carousel_19_6.tsx";
import Carousel_19_7 from "../components/Carousel_19_7.tsx";
import Carousel_19_8 from "../components/Carousel_19_8.tsx";
import Carousel_19_9 from "../components/Carousel_19_9.tsx";
import Carousel_19_10 from "../components/Carousel_19_10.tsx";
import Carousel_19_11 from "../components/Carousel_19_11.tsx";
import Carousel_19_12 from "../components/Carousel_19_12.tsx";
import Carousel_19_13 from "../components/Carousel_19_13.tsx";
import Carousel_19_14 from "../components/Carousel_19_14.tsx";
import Carousel_19_15 from "../components/Carousel_19_15.tsx";
import Carousel_19_16 from "../components/Carousel_19_16.tsx";
import Carousel_19_17 from "../components/Carousel_19_17.tsx";
import Carousel_19_18 from "../components/Carousel_19_18.tsx";
import Carousel_19_19 from "../components/Carousel_19_19.tsx";

const Page: React.FC = () => {
    return (
        <div style={{width: '1500px'}}>
            <div style={{display: 'flex', alignItems: 'center', justifyItems: 'center'}}>
                <Carousel_0_0/>

            </div>
            <div style={{display: 'flex', alignItems: 'center', justifyItems: 'center'}}>
                <Carousel_1_0/>
                <Carousel_1_1/>

            </div>
            <div style={{display: 'flex', alignItems: 'center', justifyItems: 'center'}}>
                <Carousel_2_0/>
                <Carousel_2_1/>
                <Carousel_2_2/>

            </div>
            <div style={{display: 'flex', alignItems: 'center', justifyItems: 'center'}}>
                <Carousel_3_0/>
                <Carousel_3_1/>
                <Carousel_3_2/>
                <Carousel_3_3/>

            </div>
            <div style={{display: 'flex', alignItems: 'center', justifyItems: 'center'}}>
                <Carousel_4_0/>
                <Carousel_4_1/>
                <Carousel_4_2/>
                <Carousel_4_3/>
                <Carousel_4_4/>

            </div>
            <div style={{display: 'flex', alignItems: 'center', justifyItems: 'center'}}>
                <Carousel_5_0/>
                <Carousel_5_1/>
                <Carousel_5_2/>
                <Carousel_5_3/>
                <Carousel_5_4/>
                <Carousel_5_5/>

            </div>
            <div style={{display: 'flex', alignItems: 'center', justifyItems: 'center'}}>
                <Carousel_6_0/>
                <Carousel_6_1/>
                <Carousel_6_2/>
                <Carousel_6_3/>
                <Carousel_6_4/>
                <Carousel_6_5/>
                <Carousel_6_6/>

            </div>
            <div style={{display: 'flex', alignItems: 'center', justifyItems: 'center'}}>
                <Carousel_7_0/>
                <Carousel_7_1/>
                <Carousel_7_2/>
                <Carousel_7_3/>
                <Carousel_7_4/>
                <Carousel_7_5/>
                <Carousel_7_6/>
                <Carousel_7_7/>

            </div>
            <div style={{display: 'flex', alignItems: 'center', justifyItems: 'center'}}>
                <Carousel_8_0/>
                <Carousel_8_1/>
                <Carousel_8_2/>
                <Carousel_8_3/>
                <Carousel_8_4/>
                <Carousel_8_5/>
                <Carousel_8_6/>
                <Carousel_8_7/>
                <Carousel_8_8/>

            </div>
            <div style={{display: 'flex', alignItems: 'center', justifyItems: 'center'}}>
                <Carousel_9_0/>
                <Carousel_9_1/>
                <Carousel_9_2/>
                <Carousel_9_3/>
                <Carousel_9_4/>
                <Carousel_9_5/>
                <Carousel_9_6/>
                <Carousel_9_7/>
                <Carousel_9_8/>
                <Carousel_9_9/>

            </div>
            <div style={{display: 'flex', alignItems: 'center', justifyItems: 'center'}}>
                <Carousel_10_0/>
                <Carousel_10_1/>
                <Carousel_10_2/>
                <Carousel_10_3/>
                <Carousel_10_4/>
                <Carousel_10_5/>
                <Carousel_10_6/>
                <Carousel_10_7/>
                <Carousel_10_8/>
                <Carousel_10_9/>
                <Carousel_10_10/>

            </div>
            <div style={{display: 'flex', alignItems: 'center', justifyItems: 'center'}}>
                <Carousel_11_0/>
                <Carousel_11_1/>
                <Carousel_11_2/>
                <Carousel_11_3/>
                <Carousel_11_4/>
                <Carousel_11_5/>
                <Carousel_11_6/>
                <Carousel_11_7/>
                <Carousel_11_8/>
                <Carousel_11_9/>
                <Carousel_11_10/>
                <Carousel_11_11/>

            </div>
            <div style={{display: 'flex', alignItems: 'center', justifyItems: 'center'}}>
                <Carousel_12_0/>
                <Carousel_12_1/>
                <Carousel_12_2/>
                <Carousel_12_3/>
                <Carousel_12_4/>
                <Carousel_12_5/>
                <Carousel_12_6/>
                <Carousel_12_7/>
                <Carousel_12_8/>
                <Carousel_12_9/>
                <Carousel_12_10/>
                <Carousel_12_11/>
                <Carousel_12_12/>

            </div>
            <div style={{display: 'flex', alignItems: 'center', justifyItems: 'center'}}>
                <Carousel_13_0/>
                <Carousel_13_1/>
                <Carousel_13_2/>
                <Carousel_13_3/>
                <Carousel_13_4/>
                <Carousel_13_5/>
                <Carousel_13_6/>
                <Carousel_13_7/>
                <Carousel_13_8/>
                <Carousel_13_9/>
                <Carousel_13_10/>
                <Carousel_13_11/>
                <Carousel_13_12/>
                <Carousel_13_13/>

            </div>
            <div style={{display: 'flex', alignItems: 'center', justifyItems: 'center'}}>
                <Carousel_14_0/>
                <Carousel_14_1/>
                <Carousel_14_2/>
                <Carousel_14_3/>
                <Carousel_14_4/>
                <Carousel_14_5/>
                <Carousel_14_6/>
                <Carousel_14_7/>
                <Carousel_14_8/>
                <Carousel_14_9/>
                <Carousel_14_10/>
                <Carousel_14_11/>
                <Carousel_14_12/>
                <Carousel_14_13/>
                <Carousel_14_14/>

            </div>
            <div style={{display: 'flex', alignItems: 'center', justifyItems: 'center'}}>
                <Carousel_15_0/>
                <Carousel_15_1/>
                <Carousel_15_2/>
                <Carousel_15_3/>
                <Carousel_15_4/>
                <Carousel_15_5/>
                <Carousel_15_6/>
                <Carousel_15_7/>
                <Carousel_15_8/>
                <Carousel_15_9/>
                <Carousel_15_10/>
                <Carousel_15_11/>
                <Carousel_15_12/>
                <Carousel_15_13/>
                <Carousel_15_14/>
                <Carousel_15_15/>

            </div>
            <div style={{display: 'flex', alignItems: 'center', justifyItems: 'center'}}>
                <Carousel_16_0/>
                <Carousel_16_1/>
                <Carousel_16_2/>
                <Carousel_16_3/>
                <Carousel_16_4/>
                <Carousel_16_5/>
                <Carousel_16_6/>
                <Carousel_16_7/>
                <Carousel_16_8/>
                <Carousel_16_9/>
                <Carousel_16_10/>
                <Carousel_16_11/>
                <Carousel_16_12/>
                <Carousel_16_13/>
                <Carousel_16_14/>
                <Carousel_16_15/>
                <Carousel_16_16/>

            </div>
            <div style={{display: 'flex', alignItems: 'center', justifyItems: 'center'}}>
                <Carousel_17_0/>
                <Carousel_17_1/>
                <Carousel_17_2/>
                <Carousel_17_3/>
                <Carousel_17_4/>
                <Carousel_17_5/>
                <Carousel_17_6/>
                <Carousel_17_7/>
                <Carousel_17_8/>
                <Carousel_17_9/>
                <Carousel_17_10/>
                <Carousel_17_11/>
                <Carousel_17_12/>
                <Carousel_17_13/>
                <Carousel_17_14/>
                <Carousel_17_15/>
                <Carousel_17_16/>
                <Carousel_17_17/>

            </div>
            <div style={{display: 'flex', alignItems: 'center', justifyItems: 'center'}}>
                <Carousel_18_0/>
                <Carousel_18_1/>
                <Carousel_18_2/>
                <Carousel_18_3/>
                <Carousel_18_4/>
                <Carousel_18_5/>
                <Carousel_18_6/>
                <Carousel_18_7/>
                <Carousel_18_8/>
                <Carousel_18_9/>
                <Carousel_18_10/>
                <Carousel_18_11/>
                <Carousel_18_12/>
                <Carousel_18_13/>
                <Carousel_18_14/>
                <Carousel_18_15/>
                <Carousel_18_16/>
                <Carousel_18_17/>
                <Carousel_18_18/>

            </div>
            <div style={{display: 'flex', alignItems: 'center', justifyItems: 'center'}}>
                <Carousel_19_0/>
                <Carousel_19_1/>
                <Carousel_19_2/>
                <Carousel_19_3/>
                <Carousel_19_4/>
                <Carousel_19_5/>
                <Carousel_19_6/>
                <Carousel_19_7/>
                <Carousel_19_8/>
                <Carousel_19_9/>
                <Carousel_19_10/>
                <Carousel_19_11/>
                <Carousel_19_12/>
                <Carousel_19_13/>
                <Carousel_19_14/>
                <Carousel_19_15/>
                <Carousel_19_16/>
                <Carousel_19_17/>
                <Carousel_19_18/>
                <Carousel_19_19/>

            </div>

        </div>
    );
};

export default Page;
