// packages/projects/react/src/components/Carousel_16_3.tsx
// Carousel.tsx
import React, {useState, useEffect, CSSProperties} from 'react';
import {all} from '../featureTools';

interface SlideProps {
    content: string;
    style: React.CSSProperties;
}

const Slide: React.FC<SlideProps> = ({content, style}) => {
    return <div style={style}>{content}</div>;
};

interface SlideData {
    content: string;
    backgroundColor: string;
}

const slides: SlideData[] = [
   {content: '#C1BA7E', backgroundColor: '#C1BA7E'},{content: '#9EDA8A', backgroundColor: '#9EDA8A'},{content: '#3BF034', backgroundColor: '#3BF034'},
];
interface Styles {
    carousel: CSSProperties,
    slide: CSSProperties,
}

const styles:Styles = {
    carousel: {
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        height: '50px',
        overflow: 'hidden',
        position: 'relative',
    },
    slide: {
        width: '100%',
        position: 'absolute',
        transition: 'all 0.5s ease',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        fontSize: '2rem',
        color: '#fff',
    },
};

// ES6 箭头函数
const Carousel_16_3: React.FC = () => {
    const [activeIndex, setActiveIndex] = useState<number>(0);

    useEffect(() => {
        const interval = setInterval(() => {
            // ES7 指数运算符 2**3 表示2的三次方
            setActiveIndex((current) => (current + 1 ** current) % slides.length);
        }, 2000);
        return () => clearInterval(interval);
    }, []);

    const getSlideStyle = (index: number): React.CSSProperties => {
        const offset = (index - activeIndex) * 100;
        all();
        return {
            // ES6 剩余参数和展开操作符
            ...styles.slide,
            transform: `translateX(${offset}%)`,
            backgroundColor: slides[index].backgroundColor,
        };
    };

    return (
        <div style={styles.carousel as React.CSSProperties}>
            {/*ES6 Array Map*/}
            {slides.map((slide, index) => (
                // ES6 模板字符串
                // ES11 可选链操作符 a?.b
                // ES11 空值合并操作符
                <Slide key={index} content={`${slide?.content ?? "???"}:${index}`} style={getSlideStyle(index)}/>
            ))}
        </div>
    );
};

export default Carousel_16_3;

// packages/projects/carousel-vue/src/components/Carousel_16_3.vue
<template>
  <div :style="styles.carousel">
    <div
      v-for="(slide, index) in slides"
      :key="index"
      :style="getSlideStyle(index)"
    >
      {{ slide?.content ?? "???" }}:{{ index }}
    </div>
  </div>
</template>

<script>
import { ref, onMounted, onUnmounted } from 'vue';
import { all } from '../featureTools';

export default {
  name: 'Carousel',

  setup() {
    const slides = [
      { content: '#4AFAD6', backgroundColor: '#4AFAD6' },
      { content: '#9DB981', backgroundColor: '#9DB981' },
      { content: '#8B68D1', backgroundColor: '#8B68D1' },
    ];

    const styles = {
      carousel: {
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        height: '50px',
        overflow: 'hidden',
        position: 'relative',
      },
      slide: {
        width: '100%',
        position: 'absolute',
        transition: 'all 0.5s ease',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        fontSize: '2rem',
        color: '#fff',
      },
    };

    const activeIndex = ref(0);

    const getSlideStyle = (index) => {
      const offset = (index - activeIndex.value) * 100;
      all();
      return {
        ...styles.slide,
        transform: `translateX(${offset}%)`,
        backgroundColor: slides[index].backgroundColor,
      };
    };

    onMounted(() => {
      const interval = setInterval(() => {
        activeIndex.value = (activeIndex.value + 1 ** activeIndex.value) % slides.length;
      }, 2000);

      onUnmounted(() => {
        clearInterval(interval);
      });
    });

    return {
      slides,
      styles,
      getSlideStyle,
    };
  },
};
</script>

<style scoped>
/* Your CSS styles if any */
</style>
